server:
  port: 8081

spring:
  application:
    name: creative-resizer

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  data:
    mongodb:
      uri: mongodb://localhost:27017/creative_resizer

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

creative:
  storage:
    upload-dir: /app/storage/uploads
    output-dir: /app/storage/outputs
    zip-dir: /app/storage/zips
  worker:
    url: http://banner-worker:5000
  openai:
    api-key: ${OPENAI_API_KEY:}

---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      uri: mongodb://localhost:27017/creative_resizer

  rabbitmq:
    host: localhost

creative:
  storage:
    upload-dir: C:/company/storage/creative/uploads
    output-dir: C:/company/storage/creative/outputs
    zip-dir: C:/company/storage/creative/zips
  worker:
    url: http://localhost:5000

---
spring:
  config:
    activate:
      on-profile: prod

  data:
    mongodb:
      uri: ${MONGODB_URI}

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}

creative:
  worker:
    url: http://creative-worker:5000
  openai:
    api-key: ${OPENAI_API_KEY}
