"""Stage 21 Bundle C-1: Reason code constants.

All reason codes used in VerdictResult.reasonCodes.
Codes are uppercase snake_case strings — deterministic ordering in sorted output.
"""

# ── Technical ─────────────────────────────────────────────────────────────────
TECH_PROVIDER_FAILED = "TECH_PROVIDER_FAILED"
TECH_OUTPUT_MISSING = "TECH_OUTPUT_MISSING"
TECH_OUTPUT_SIZE_INVALID = "TECH_OUTPUT_SIZE_INVALID"
TECH_OUTPUT_FILE_EMPTY = "TECH_OUTPUT_FILE_EMPTY"
TECH_OUTPUT_DECODE_FAILED = "TECH_OUTPUT_DECODE_FAILED"
TECH_FALLBACK_USED = "TECH_FALLBACK_USED"
TECH_SMART_FIT_FALLBACK = "TECH_SMART_FIT_FALLBACK"
TECH_BLUR_FILL_FALLBACK = "TECH_BLUR_FILL_FALLBACK"
TECH_NATIVE_FALLBACK = "TECH_NATIVE_FALLBACK"
TECH_EXCEPTION_OCCURRED = "TECH_EXCEPTION_OCCURRED"
TECH_FAIL_CLOSED_VIOLATED = "TECH_FAIL_CLOSED_VIOLATED"
TECH_NO_AI_PROVIDER = "TECH_NO_AI_PROVIDER"

# ── Extraction ────────────────────────────────────────────────────────────────
EXTRACTION_REQUIRED_ROLE_MISSING = "EXTRACTION_REQUIRED_ROLE_MISSING"
EXTRACTION_DUPLICATE_OBJECT_ID = "EXTRACTION_DUPLICATE_OBJECT_ID"
EXTRACTION_INVALID_BBOX = "EXTRACTION_INVALID_BBOX"
EXTRACTION_EMPTY_PIXEL_DATA = "EXTRACTION_EMPTY_PIXEL_DATA"
EXTRACTION_INVALID_ASPECT_RATIO = "EXTRACTION_INVALID_ASPECT_RATIO"
EXTRACTION_LOW_CONFIDENCE_REQUIRED_OBJECT = "EXTRACTION_LOW_CONFIDENCE_REQUIRED_OBJECT"
EXTRACTION_MANIFEST_BUILD_FAILED = "EXTRACTION_MANIFEST_BUILD_FAILED"
EXTRACTION_NO_FOREGROUND_LAYERS = "EXTRACTION_NO_FOREGROUND_LAYERS"

# ── Composition ───────────────────────────────────────────────────────────────
COMPOSITION_DUPLICATE_OBJECT = "COMPOSITION_DUPLICATE_OBJECT"
COMPOSITION_REQUIRED_OBJECT_SKIPPED = "COMPOSITION_REQUIRED_OBJECT_SKIPPED"
COMPOSITION_OBJECT_NOT_COMPOSITED = "COMPOSITION_OBJECT_NOT_COMPOSITED"
COMPOSITION_OBJECT_COMPOSITED_MULTIPLE_TIMES = "COMPOSITION_OBJECT_COMPOSITED_MULTIPLE_TIMES"
COMPOSITION_COUNTER_MISMATCH = "COMPOSITION_COUNTER_MISMATCH"
COMPOSITION_WRONG_OWNER_COMPOSITED = "COMPOSITION_WRONG_OWNER_COMPOSITED"
COMPOSITION_COMPOSITOR_FAILED = "COMPOSITION_COMPOSITOR_FAILED"

# ── Layout ────────────────────────────────────────────────────────────────────
LAYOUT_SAFE_ZONE_UNAVAILABLE = "LAYOUT_SAFE_ZONE_UNAVAILABLE"
LAYOUT_SAFE_ZONE_VIOLATION = "LAYOUT_SAFE_ZONE_VIOLATION"
LAYOUT_REQUIRED_OBJECT_CLIPPED = "LAYOUT_REQUIRED_OBJECT_CLIPPED"
LAYOUT_REQUIRED_OBJECT_OUT_OF_BOUNDS = "LAYOUT_REQUIRED_OBJECT_OUT_OF_BOUNDS"
LAYOUT_FORBIDDEN_OVERLAP = "LAYOUT_FORBIDDEN_OVERLAP"
LAYOUT_REQUIRED_OBJECT_MISSING = "LAYOUT_REQUIRED_OBJECT_MISSING"
LAYOUT_NO_VALID_CANDIDATE = "LAYOUT_NO_VALID_CANDIDATE"
LAYOUT_PLAN_FAILED = "LAYOUT_PLAN_FAILED"
LAYOUT_ENGINE_ERROR = "LAYOUT_ENGINE_ERROR"
LAYOUT_HARD_FAIL = "LAYOUT_HARD_FAIL"

# ── Semantic Scene Cleanup (Bundle D-1) ──────────────────────────────────────
TECH_SEMANTIC_SCENE_PROVIDER_INPUT_INVALID = "TECH_SEMANTIC_SCENE_PROVIDER_INPUT_INVALID"
TECH_SEMANTIC_SCENE_PLATE_MISSING = "TECH_SEMANTIC_SCENE_PLATE_MISSING"
TECH_SEMANTIC_SCENE_BACKGROUND_PLATE_USED = "TECH_SEMANTIC_SCENE_BACKGROUND_PLATE_USED"
TECH_SEMANTIC_SCENE_LEGACY_MASK_USED = "TECH_SEMANTIC_SCENE_LEGACY_MASK_USED"
TECH_SEMANTIC_SCENE_BBOX_MASK_USED = "TECH_SEMANTIC_SCENE_BBOX_MASK_USED"

# ── Extraction D-2 (flattened input — D-2 not implemented) ───────────────────
EXTRACTION_D2_REQUIRED_FOR_FLATTENED_INPUT = "EXTRACTION_D2_REQUIRED_FOR_FLATTENED_INPUT"

# ── Visual ────────────────────────────────────────────────────────────────────
VISUAL_NOT_TESTED = "VISUAL_NOT_TESTED"

# ── Overall ───────────────────────────────────────────────────────────────────
OVERALL_REQUIRED_VERDICT_FAILED = "OVERALL_REQUIRED_VERDICT_FAILED"
OVERALL_REQUIRED_VERDICT_NOT_TESTED = "OVERALL_REQUIRED_VERDICT_NOT_TESTED"
OVERALL_ALL_REQUIRED_NOT_APPLICABLE = "OVERALL_ALL_REQUIRED_NOT_APPLICABLE"
OVERALL_VERDICT_PIPELINE_EXCEPTION = "OVERALL_VERDICT_PIPELINE_EXCEPTION"
OVERALL_REQUIRED_VERDICT_MISSING = "OVERALL_REQUIRED_VERDICT_MISSING"

# ── Ordered set for deterministic output ─────────────────────────────────────

ALL_CODES = sorted([
    TECH_PROVIDER_FAILED, TECH_OUTPUT_MISSING, TECH_OUTPUT_SIZE_INVALID,
    TECH_OUTPUT_FILE_EMPTY, TECH_OUTPUT_DECODE_FAILED, TECH_FALLBACK_USED,
    TECH_SMART_FIT_FALLBACK, TECH_BLUR_FILL_FALLBACK, TECH_NATIVE_FALLBACK,
    TECH_EXCEPTION_OCCURRED, TECH_FAIL_CLOSED_VIOLATED, TECH_NO_AI_PROVIDER,
    TECH_SEMANTIC_SCENE_PROVIDER_INPUT_INVALID, TECH_SEMANTIC_SCENE_PLATE_MISSING,
    TECH_SEMANTIC_SCENE_BACKGROUND_PLATE_USED, TECH_SEMANTIC_SCENE_LEGACY_MASK_USED,
    TECH_SEMANTIC_SCENE_BBOX_MASK_USED,
    EXTRACTION_REQUIRED_ROLE_MISSING, EXTRACTION_DUPLICATE_OBJECT_ID,
    EXTRACTION_INVALID_BBOX, EXTRACTION_EMPTY_PIXEL_DATA,
    EXTRACTION_INVALID_ASPECT_RATIO, EXTRACTION_LOW_CONFIDENCE_REQUIRED_OBJECT,
    EXTRACTION_MANIFEST_BUILD_FAILED, EXTRACTION_NO_FOREGROUND_LAYERS,
    EXTRACTION_D2_REQUIRED_FOR_FLATTENED_INPUT,
    COMPOSITION_DUPLICATE_OBJECT, COMPOSITION_REQUIRED_OBJECT_SKIPPED,
    COMPOSITION_OBJECT_NOT_COMPOSITED, COMPOSITION_OBJECT_COMPOSITED_MULTIPLE_TIMES,
    COMPOSITION_COUNTER_MISMATCH, COMPOSITION_WRONG_OWNER_COMPOSITED,
    COMPOSITION_COMPOSITOR_FAILED,
    LAYOUT_SAFE_ZONE_UNAVAILABLE, LAYOUT_SAFE_ZONE_VIOLATION,
    LAYOUT_REQUIRED_OBJECT_CLIPPED, LAYOUT_REQUIRED_OBJECT_OUT_OF_BOUNDS,
    LAYOUT_FORBIDDEN_OVERLAP, LAYOUT_REQUIRED_OBJECT_MISSING,
    LAYOUT_NO_VALID_CANDIDATE, LAYOUT_PLAN_FAILED, LAYOUT_ENGINE_ERROR,
    LAYOUT_HARD_FAIL,
    VISUAL_NOT_TESTED,
    OVERALL_REQUIRED_VERDICT_FAILED, OVERALL_REQUIRED_VERDICT_NOT_TESTED,
    OVERALL_ALL_REQUIRED_NOT_APPLICABLE, OVERALL_VERDICT_PIPELINE_EXCEPTION,
    OVERALL_REQUIRED_VERDICT_MISSING,
])
