"""Stage 21 Bundle C-1: Reason code constants.

All reason codes used in VerdictResult.reasonCodes.
Codes are uppercase snake_case strings — deterministic ordering in sorted output.
"""

# ── Technical ─────────────────────────────────────────────────────────────────
TECH_PROVIDER_FAILED = "TECH_PROVIDER_FAILED"
TECH_OUTPUT_MISSING = "TECH_OUTPUT_MISSING"
TECH_OUTPUT_SIZE_INVALID = "TECH_OUTPUT_SIZE_INVALID"
TECH_OUTPUT_FILE_EMPTY = "TECH_OUTPUT_FILE_EMPTY"
TECH_OUTPUT_DECODE_FAILED = "TECH_OUTPUT_DECODE_FAILED"
TECH_FALLBACK_USED = "TECH_FALLBACK_USED"
TECH_SMART_FIT_FALLBACK = "TECH_SMART_FIT_FALLBACK"
TECH_BLUR_FILL_FALLBACK = "TECH_BLUR_FILL_FALLBACK"
TECH_NATIVE_FALLBACK = "TECH_NATIVE_FALLBACK"
TECH_EXCEPTION_OCCURRED = "TECH_EXCEPTION_OCCURRED"
TECH_FAIL_CLOSED_VIOLATED = "TECH_FAIL_CLOSED_VIOLATED"
TECH_NO_AI_PROVIDER = "TECH_NO_AI_PROVIDER"

# ── Extraction ────────────────────────────────────────────────────────────────
EXTRACTION_REQUIRED_ROLE_MISSING = "EXTRACTION_REQUIRED_ROLE_MISSING"
EXTRACTION_DUPLICATE_OBJECT_ID = "EXTRACTION_DUPLICATE_OBJECT_ID"
EXTRACTION_INVALID_BBOX = "EXTRACTION_INVALID_BBOX"
EXTRACTION_EMPTY_PIXEL_DATA = "EXTRACTION_EMPTY_PIXEL_DATA"
EXTRACTION_INVALID_ASPECT_RATIO = "EXTRACTION_INVALID_ASPECT_RATIO"
EXTRACTION_LOW_CONFIDENCE_REQUIRED_OBJECT = "EXTRACTION_LOW_CONFIDENCE_REQUIRED_OBJECT"
EXTRACTION_MANIFEST_BUILD_FAILED = "EXTRACTION_MANIFEST_BUILD_FAILED"
EXTRACTION_NO_FOREGROUND_LAYERS = "EXTRACTION_NO_FOREGROUND_LAYERS"

# ── Composition ───────────────────────────────────────────────────────────────
COMPOSITION_DUPLICATE_OBJECT = "COMPOSITION_DUPLICATE_OBJECT"
COMPOSITION_REQUIRED_OBJECT_SKIPPED = "COMPOSITION_REQUIRED_OBJECT_SKIPPED"
COMPOSITION_OBJECT_NOT_COMPOSITED = "COMPOSITION_OBJECT_NOT_COMPOSITED"
COMPOSITION_OBJECT_COMPOSITED_MULTIPLE_TIMES = "COMPOSITION_OBJECT_COMPOSITED_MULTIPLE_TIMES"
COMPOSITION_COUNTER_MISMATCH = "COMPOSITION_COUNTER_MISMATCH"
COMPOSITION_WRONG_OWNER_COMPOSITED = "COMPOSITION_WRONG_OWNER_COMPOSITED"
COMPOSITION_COMPOSITOR_FAILED = "COMPOSITION_COMPOSITOR_FAILED"

# ── Layout ────────────────────────────────────────────────────────────────────
LAYOUT_SAFE_ZONE_UNAVAILABLE = "LAYOUT_SAFE_ZONE_UNAVAILABLE"
LAYOUT_SAFE_ZONE_VIOLATION = "LAYOUT_SAFE_ZONE_VIOLATION"
LAYOUT_REQUIRED_OBJECT_CLIPPED = "LAYOUT_REQUIRED_OBJECT_CLIPPED"
LAYOUT_REQUIRED_OBJECT_OUT_OF_BOUNDS = "LAYOUT_REQUIRED_OBJECT_OUT_OF_BOUNDS"
LAYOUT_FORBIDDEN_OVERLAP = "LAYOUT_FORBIDDEN_OVERLAP"
LAYOUT_REQUIRED_OBJECT_MISSING = "LAYOUT_REQUIRED_OBJECT_MISSING"
LAYOUT_NO_VALID_CANDIDATE = "LAYOUT_NO_VALID_CANDIDATE"
LAYOUT_PLAN_FAILED = "LAYOUT_PLAN_FAILED"
LAYOUT_ENGINE_ERROR = "LAYOUT_ENGINE_ERROR"
LAYOUT_HARD_FAIL = "LAYOUT_HARD_FAIL"

# ── Semantic Scene Cleanup (Bundle D-1) ──────────────────────────────────────
TECH_SEMANTIC_SCENE_PROVIDER_INPUT_INVALID = "TECH_SEMANTIC_SCENE_PROVIDER_INPUT_INVALID"
TECH_SEMANTIC_SCENE_PLATE_MISSING = "TECH_SEMANTIC_SCENE_PLATE_MISSING"
TECH_SEMANTIC_SCENE_BACKGROUND_PLATE_USED = "TECH_SEMANTIC_SCENE_BACKGROUND_PLATE_USED"
TECH_SEMANTIC_SCENE_LEGACY_MASK_USED = "TECH_SEMANTIC_SCENE_LEGACY_MASK_USED"
TECH_SEMANTIC_SCENE_BBOX_MASK_USED = "TECH_SEMANTIC_SCENE_BBOX_MASK_USED"

# ── Extraction D-2 ────────────────────────────────────────────────────────────
EXTRACTION_D2_REQUIRED_FOR_FLATTENED_INPUT = "EXTRACTION_D2_REQUIRED_FOR_FLATTENED_INPUT"

# Object analysis failures
EXTRACTION_D2_OBJECT_ANALYSIS_FAILED = "EXTRACTION_D2_OBJECT_ANALYSIS_FAILED"
EXTRACTION_D2_OBJECT_ANALYSIS_INVALID_RESPONSE = "EXTRACTION_D2_OBJECT_ANALYSIS_INVALID_RESPONSE"
EXTRACTION_D2_NO_OBJECTS_DETECTED = "EXTRACTION_D2_NO_OBJECTS_DETECTED"

# Source reference failures
EXTRACTION_D2_SOURCE_REFERENCE_BUILD_FAILED = "EXTRACTION_D2_SOURCE_REFERENCE_BUILD_FAILED"
EXTRACTION_D2_SOURCE_REFERENCE_BLANK = "EXTRACTION_D2_SOURCE_REFERENCE_BLANK"

# Mask extraction failures
EXTRACTION_D2_PAIRED_DIFFERENCE_FAILED = "EXTRACTION_D2_PAIRED_DIFFERENCE_FAILED"
EXTRACTION_D2_RAW_MASK_EMPTY = "EXTRACTION_D2_RAW_MASK_EMPTY"
EXTRACTION_D2_RAW_MASK_SATURATED = "EXTRACTION_D2_RAW_MASK_SATURATED"
EXTRACTION_D2_MASK_COMPONENT_COUNT_EXCESSIVE = "EXTRACTION_D2_MASK_COMPONENT_COUNT_EXCESSIVE"

# Quality validation failures
EXTRACTION_D2_ALPHA_COVERAGE_TOO_LOW = "EXTRACTION_D2_ALPHA_COVERAGE_TOO_LOW"
EXTRACTION_D2_ALPHA_COVERAGE_TOO_HIGH = "EXTRACTION_D2_ALPHA_COVERAGE_TOO_HIGH"
EXTRACTION_D2_BACKGROUND_CONTAMINATION_DETECTED = "EXTRACTION_D2_BACKGROUND_CONTAMINATION_DETECTED"
EXTRACTION_D2_OPAQUE_BBOX_CROP_DETECTED = "EXTRACTION_D2_OPAQUE_BBOX_CROP_DETECTED"
EXTRACTION_D2_BORDER_ALPHA_RATIO_TOO_HIGH = "EXTRACTION_D2_BORDER_ALPHA_RATIO_TOO_HIGH"

# Required / dedup / manifest
EXTRACTION_D2_REQUIRED_OBJECT_EXTRACTION_FAILED = "EXTRACTION_D2_REQUIRED_OBJECT_EXTRACTION_FAILED"
EXTRACTION_D2_REQUIRED_OBJECT_MISSING_AFTER_DEDUP = "EXTRACTION_D2_REQUIRED_OBJECT_MISSING_AFTER_DEDUP"
EXTRACTION_D2_NATIVE_VIRTUAL_DUPLICATE = "EXTRACTION_D2_NATIVE_VIRTUAL_DUPLICATE"
EXTRACTION_D2_GROUP_OBJECT_INCOMPLETE = "EXTRACTION_D2_GROUP_OBJECT_INCOMPLETE"
EXTRACTION_D2_MANIFEST_EMPTY_AFTER_EXTRACTION = "EXTRACTION_D2_MANIFEST_EMPTY_AFTER_EXTRACTION"

# Applicability
EXTRACTION_D2_VIRTUAL_FOREGROUND_NOT_APPLICABLE = "EXTRACTION_D2_VIRTUAL_FOREGROUND_NOT_APPLICABLE"
EXTRACTION_D2_SOURCE_TYPE_INELIGIBLE = "EXTRACTION_D2_SOURCE_TYPE_INELIGIBLE"
EXTRACTION_D2_NO_OBJECTS_AFTER_NATIVE_DEDUP = "EXTRACTION_D2_NO_OBJECTS_AFTER_NATIVE_DEDUP"

# Tech D-2 guards (4 codes)
TECH_D2_VIRTUAL_LAYER_USED_AS_OPAQUE_BBOX = "TECH_D2_VIRTUAL_LAYER_USED_AS_OPAQUE_BBOX"
TECH_D2_HUMAN_SUBJECT_EXTRACTED_AS_VIRTUAL = "TECH_D2_HUMAN_SUBJECT_EXTRACTED_AS_VIRTUAL"
TECH_D2_NATIVE_PRIORITY_VIOLATED = "TECH_D2_NATIVE_PRIORITY_VIOLATED"
TECH_D2_SCENE_REFERENCE_CONTAMINATED = "TECH_D2_SCENE_REFERENCE_CONTAMINATED"

# ── Visual ────────────────────────────────────────────────────────────────────
VISUAL_NOT_TESTED = "VISUAL_NOT_TESTED"

# ── Overall ───────────────────────────────────────────────────────────────────
OVERALL_REQUIRED_VERDICT_FAILED = "OVERALL_REQUIRED_VERDICT_FAILED"
OVERALL_REQUIRED_VERDICT_NOT_TESTED = "OVERALL_REQUIRED_VERDICT_NOT_TESTED"
OVERALL_ALL_REQUIRED_NOT_APPLICABLE = "OVERALL_ALL_REQUIRED_NOT_APPLICABLE"
OVERALL_VERDICT_PIPELINE_EXCEPTION = "OVERALL_VERDICT_PIPELINE_EXCEPTION"
OVERALL_REQUIRED_VERDICT_MISSING = "OVERALL_REQUIRED_VERDICT_MISSING"

# ── Ordered set for deterministic output ─────────────────────────────────────

ALL_CODES = sorted([
    TECH_PROVIDER_FAILED, TECH_OUTPUT_MISSING, TECH_OUTPUT_SIZE_INVALID,
    TECH_OUTPUT_FILE_EMPTY, TECH_OUTPUT_DECODE_FAILED, TECH_FALLBACK_USED,
    TECH_SMART_FIT_FALLBACK, TECH_BLUR_FILL_FALLBACK, TECH_NATIVE_FALLBACK,
    TECH_EXCEPTION_OCCURRED, TECH_FAIL_CLOSED_VIOLATED, TECH_NO_AI_PROVIDER,
    TECH_SEMANTIC_SCENE_PROVIDER_INPUT_INVALID, TECH_SEMANTIC_SCENE_PLATE_MISSING,
    TECH_SEMANTIC_SCENE_BACKGROUND_PLATE_USED, TECH_SEMANTIC_SCENE_LEGACY_MASK_USED,
    TECH_SEMANTIC_SCENE_BBOX_MASK_USED,
    EXTRACTION_REQUIRED_ROLE_MISSING, EXTRACTION_DUPLICATE_OBJECT_ID,
    EXTRACTION_INVALID_BBOX, EXTRACTION_EMPTY_PIXEL_DATA,
    EXTRACTION_INVALID_ASPECT_RATIO, EXTRACTION_LOW_CONFIDENCE_REQUIRED_OBJECT,
    EXTRACTION_MANIFEST_BUILD_FAILED, EXTRACTION_NO_FOREGROUND_LAYERS,
    EXTRACTION_D2_REQUIRED_FOR_FLATTENED_INPUT,
    EXTRACTION_D2_OBJECT_ANALYSIS_FAILED, EXTRACTION_D2_OBJECT_ANALYSIS_INVALID_RESPONSE,
    EXTRACTION_D2_NO_OBJECTS_DETECTED,
    EXTRACTION_D2_SOURCE_REFERENCE_BUILD_FAILED, EXTRACTION_D2_SOURCE_REFERENCE_BLANK,
    EXTRACTION_D2_PAIRED_DIFFERENCE_FAILED, EXTRACTION_D2_RAW_MASK_EMPTY,
    EXTRACTION_D2_RAW_MASK_SATURATED, EXTRACTION_D2_MASK_COMPONENT_COUNT_EXCESSIVE,
    EXTRACTION_D2_ALPHA_COVERAGE_TOO_LOW, EXTRACTION_D2_ALPHA_COVERAGE_TOO_HIGH,
    EXTRACTION_D2_BACKGROUND_CONTAMINATION_DETECTED, EXTRACTION_D2_OPAQUE_BBOX_CROP_DETECTED,
    EXTRACTION_D2_BORDER_ALPHA_RATIO_TOO_HIGH,
    EXTRACTION_D2_REQUIRED_OBJECT_EXTRACTION_FAILED,
    EXTRACTION_D2_REQUIRED_OBJECT_MISSING_AFTER_DEDUP,
    EXTRACTION_D2_NATIVE_VIRTUAL_DUPLICATE, EXTRACTION_D2_GROUP_OBJECT_INCOMPLETE,
    EXTRACTION_D2_MANIFEST_EMPTY_AFTER_EXTRACTION,
    EXTRACTION_D2_VIRTUAL_FOREGROUND_NOT_APPLICABLE, EXTRACTION_D2_SOURCE_TYPE_INELIGIBLE,
    EXTRACTION_D2_NO_OBJECTS_AFTER_NATIVE_DEDUP,
    TECH_D2_VIRTUAL_LAYER_USED_AS_OPAQUE_BBOX, TECH_D2_HUMAN_SUBJECT_EXTRACTED_AS_VIRTUAL,
    TECH_D2_NATIVE_PRIORITY_VIOLATED, TECH_D2_SCENE_REFERENCE_CONTAMINATED,
    COMPOSITION_DUPLICATE_OBJECT, COMPOSITION_REQUIRED_OBJECT_SKIPPED,
    COMPOSITION_OBJECT_NOT_COMPOSITED, COMPOSITION_OBJECT_COMPOSITED_MULTIPLE_TIMES,
    COMPOSITION_COUNTER_MISMATCH, COMPOSITION_WRONG_OWNER_COMPOSITED,
    COMPOSITION_COMPOSITOR_FAILED,
    LAYOUT_SAFE_ZONE_UNAVAILABLE, LAYOUT_SAFE_ZONE_VIOLATION,
    LAYOUT_REQUIRED_OBJECT_CLIPPED, LAYOUT_REQUIRED_OBJECT_OUT_OF_BOUNDS,
    LAYOUT_FORBIDDEN_OVERLAP, LAYOUT_REQUIRED_OBJECT_MISSING,
    LAYOUT_NO_VALID_CANDIDATE, LAYOUT_PLAN_FAILED, LAYOUT_ENGINE_ERROR,
    LAYOUT_HARD_FAIL,
    VISUAL_NOT_TESTED,
    OVERALL_REQUIRED_VERDICT_FAILED, OVERALL_REQUIRED_VERDICT_NOT_TESTED,
    OVERALL_ALL_REQUIRED_NOT_APPLICABLE, OVERALL_VERDICT_PIPELINE_EXCEPTION,
    OVERALL_REQUIRED_VERDICT_MISSING,
])
