"""TYPE D outpaint 프롬프트.

프롬프트만 바꿀 때는 이 파일만 수정.
"""

# v7 2026-07-31: 좌우 분리 지시 + 우측 블랙 패널 + 품질 목표 명시
OUTPAINT_PROMPT = (
    "This is a constrained outpainting and canvas-extension task.\n\n"
    "Target result:\n"
    "- Final canvas size: 1200 × 560 pixels\n"
    "- The resized original advertisement is centered in the canvas.\n"
    "- Preserve the existing center advertisement.\n"
    "- Generate only the masked left and right extension areas and the narrow masked overlap near each boundary.\n\n"
    "Scene analysis:\n"
    "- The left half is a bright skincare photograph.\n"
    "- A woman is leaning against a large white satin-like fabric.\n"
    "- At the left boundary, the upper area contains a soft pale blue-white photographic background.\n"
    "- At the left boundary, the middle and lower areas contain the same existing white satin fabric.\n"
    "- The fabric has smooth curved contours, large soft folds, pearly highlights, subtle blue-gray shadows, and a glossy photographic texture.\n"
    "- The right half is a clean black advertising panel containing the existing product and Korean promotional text.\n"
    "- The right canvas boundary contains only the black panel background.\n\n"
    "Editing instructions:\n\n"
    "LEFT EXTENSION:\n"
    "Extend every existing visual element that reaches the left source boundary.\n\n"
    "The white satin fabric is an existing foreground element and must continue naturally into the new left area.\n"
    "Do not treat the entire left extension as plain background.\n\n"
    "Continue the fabric with:\n"
    "- the same upper contour direction\n"
    "- continuous large folds and curvature\n"
    "- matching pearly white highlights\n"
    "- matching soft blue-gray shadows\n"
    "- matching satin texture, lighting, focus, and photographic softness\n\n"
    "The fabric should occupy the middle and lower parts of the left extension according to the structure visible at the source boundary.\n\n"
    "In the upper-left area, continue the soft pale blue-white background naturally.\n"
    "Match its brightness, blur, color temperature, and lighting gradient.\n\n"
    "Important left-side prohibitions:\n"
    "- do not replace the existing fabric with plain pale-blue background\n"
    "- do not stop the fabric at the original boundary\n"
    "- do not create a vertical rectangular patch\n"
    "- do not mirror, stretch, smear, or duplicate edge pixels\n"
    "- do not create a disconnected new piece of fabric\n"
    "- do not create a visible seam, tone break, or abrupt contour change\n\n"
    "RIGHT EXTENSION:\n"
    "Continue only the existing black advertising panel.\n"
    "Match the original black tone, subtle depth, and any slight tonal variation near the boundary.\n\n"
    "Do not add:\n"
    "- new text\n"
    "- new Korean characters\n"
    "- products\n"
    "- logos\n"
    "- icons\n"
    "- highlights\n"
    "- decorative graphics\n\n"
    "PRESERVATION:\n"
    "Do not redesign or reinterpret the existing advertisement.\n"
    "Do not modify the woman, face, hair, skin, fabric inside the protected region, product, product label, Korean text, typography, spacing, layout, or colors.\n\n"
    "QUALITY TARGET:\n"
    "The completed banner must look as though the original photograph and black advertising layout were created at 1200 × 560 from the beginning.\n\n"
    "The left fabric must continue geometrically and photographically across the old boundary.\n"
    "The final result must contain no visible stitching, no vertical seam, no flat padding, and no artificial edge-fill appearance."
)
