"""TYPE D outpaint 프롬프트.

프롬프트만 바꿀 때는 이 파일만 수정.
"""

# v8 2026-07-31: 패브릭 윤곽 연속성 최우선 + 엄격한 공간 규칙 + 최고 우선순위 명시
OUTPAINT_PROMPT = (
    "This is a constrained outpainting task for an existing advertisement.\n\n"
    "Target canvas:\n"
    "- 1200 × 560 pixels\n\n"
    "Editing scope:\n"
    "- Edit only the supplied masked side-extension regions and the narrow overlap region.\n"
    "- Keep the protected center advertisement unchanged.\n"
    "- Do not redesign, reinterpret, or regenerate the full advertisement.\n\n"
    "SCENE STRUCTURE:\n"
    "- The left side contains a bright skincare photograph.\n"
    "- A large white satin fabric reaches the original left boundary.\n"
    "- The upper-left boundary contains a pale blue-white blurred background.\n"
    "- The middle-left and lower-left boundary contain the existing white satin fabric.\n"
    "- The right side contains a black advertising panel.\n\n"
    "PRIMARY LEFT-SIDE REQUIREMENT:\n"
    "The existing white satin fabric must continue beyond the original left boundary as one continuous physical surface.\n\n"
    "The fabric is not background decoration.\n"
    "It is an existing foreground object that extends outside the original frame.\n\n"
    "Continue the fabric's visible outer contour smoothly into the new left extension.\n\n"
    "The contour must:\n"
    "- begin exactly from the fabric edge visible at the original boundary\n"
    "- follow the same natural curve and direction\n"
    "- remain continuous without interruption\n"
    "- extend naturally toward the new left canvas edge\n"
    "- preserve the same shape logic, perspective, and visual depth\n\n"
    "Continue the fabric surface with:\n"
    "- broad natural folds\n"
    "- smooth curvature\n"
    "- pearly white highlights\n"
    "- soft blue-gray shadows\n"
    "- satin-like reflective texture\n"
    "- matching light direction\n"
    "- matching photographic softness and focus\n\n"
    "LEFT-SIDE SPATIAL RULES:\n"
    "- In the upper-left area, continue the pale blue-white photographic background.\n"
    "- In the middle-left and lower-left areas, continue the existing white satin fabric.\n"
    "- Wherever fabric touches the original left boundary, fabric must continue into the generated area.\n"
    "- Do not replace those fabric regions with plain background.\n\n"
    "STRICT CONTOUR RULES:\n"
    "- do not stop the fabric at the original boundary\n"
    "- do not flatten or erase the fabric contour\n"
    "- do not create a vertical cut line\n"
    "- do not replace the fabric with a pale blue or white background patch\n"
    "- do not create a disconnected second piece of fabric\n"
    "- do not create a new fabric edge that conflicts with the existing contour\n"
    "- do not mirror, stretch, smear, or duplicate boundary pixels\n"
    "- do not generate hair, skin, a person, hands, text, logos, or products in the extension\n\n"
    "RIGHT EXTENSION:\n"
    "Continue only the existing black advertising panel.\n"
    "Match its black tone and subtle tonal depth.\n"
    "Do not add text, products, logos, icons, highlights, or decorative graphics.\n\n"
    "PRESERVATION:\n"
    "Do not modify the woman, face, hair, skin, expression, blue cream, clothing, product, product label, Korean text, typography, layout, or colors inside the protected region.\n\n"
    "QUALITY TARGET:\n"
    "The new left area must look like the same satin fabric and photographic background naturally existed outside the original frame.\n\n"
    "The fabric's outer silhouette must be geometrically continuous across the old boundary.\n\n"
    "The final result must contain:\n"
    "- no visible seam\n"
    "- no broken fabric outline\n"
    "- no abrupt angle change\n"
    "- no rectangular patch\n"
    "- no flat padding appearance\n"
    "- no artificial boundary\n\n"
    "Highest priority:\n"
    "Preserve and extend the exact directional flow of the existing white fabric contour before matching general color or background tone."
)
